### ISSUE TITLE
Функционал отвечающая за работу с денежными значениями

### ISSUE THREAD

**Issue by dmowski** [yandex-shri-minsk-2016/foodhub#141]
Идея в том, чтобы сделать сервис(Хэлпер) с функциями которые будут помогать правильно оформлять цены, и в будущем (возможно) работать с денежными значениями.
Например на вход функции отдаем число 245456 (или строку), а получаем строку "245 456 р."
"2542.4546" =>  "2 542,45 р."

**Comment by ant478** [comment]
Это делается одной строчкой, не вижу смысла выносить куда-то.
`parseInt(price).toLocaleString('ru') + ' р.'`

**Comment by dmowski** [comment]
(уже) в двух компонентах используется один и тотже код(parseInt(price).toLocaleString('ru') + ' р.'). Это дублирование кода как ни крути. 
Если вдруг нам нужно будет изменить общее представление цены(пример 400р 20к), нам нужно будет редактировать в двух (может быть больше местах).
Легче вынести всё это в отдельный(легковесный) сервис, который будет отвечать за оформление цены. Так легче будет создавать компонеты. Ты вбросил своё "г" в  функцию, а в результате получил то, что гарантированно можно выводить в шаблоне (и там(в шаблоне) не будет непонятных для пользователя "NaN" или "0000000.0 р" или прочей фигни), а будет что-то осмысленное и понятное. Как по мне лече написать MoneyHelper.GetMoney(value) чем (parseInt(price).toLocaleString('ru') + ' р.') вот сходу, что означете  toLocaleString ?

**Comment by dmowski** [comment]
или например в компонент приходит массив или ".". 
(как понимаю js в аргументы js может прилететь всё что угодно)
т.е. каждый компонент будет анализировать эти данные по своему.

**Comment by ant478** [comment]
Идея выносить в отдельный модуль то что используется несколько раз сама по себе не плохая, но  это не настолько критично сейчас. Давай сейчас сосредоточимся на более приоритетных задачах.
