### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by dmowski** [yandex-shri-minsk-2016/foodhub#27]
Отрисовать и описать

- [x] Шапка сайта
- [x] Элементы формы
- [x] Кнопки
- [x] Табы
- [x] Блок с заказом другого пользователя
- [x] Блоки с отображением товаровов в разных состояниях
- [x] Шрифты
- [x] Цвета
- [x] Страницы
- [x] Логотип

**Comment by dmowski** [comment]
Картинка с описанием:
1. Шапка сайта
2. Элементы формы
3. Кнопки
4. Табы
5. Блок с заказом другого пользователя
6. Блоки с отображением товарова в разных состояниях
https://drive.google.com/file/d/0B_bWgyWObsZBZFFVY0tRSGd2blE/view?usp=sharing

**Comment by dmowski** [comment]
**Шрифты**
**Roboto** Regular(Normal 400), Bold(Bold 700), Medium(Medium 500)
https://www.google.com/fonts#UsePlace:use/Collection:Roboto

Есть 3 типа размера для заголовков
35px - Используется для описания страниц
24px и 16px

**Цвета**
#F2F2F2 - Фон страницы(body)
#FFFFFF - Фон блоков (Карточек)
#333333 - Темный фон (Фон формы выбора доставки)
#4CAF50 - Основной цвет (Зелёный)

https://drive.google.com/file/d/0B_bWgyWObsZBZ1lUZmxpcFNkSXM/view?usp=sharing

**Comment by dmowski** [comment]
**Логотип**
https://drive.google.com/folderview?id=0B_bWgyWObsZBN2FsWVdjTFpEWDA&usp=sharing

**Comment by dmowski** [comment]
**Страницы**
- [x] Авторизация
- [x] Личный профиль
- [x] Список сессий
- [ ] Новая сессия
- [ ] Просмотр чужой сессии
- [ ] Просмотр своей сессии
- [x] Подтверждение заказа

https://drive.google.com/folderview?id=0B_bWgyWObsZBM2N4T2RUQnpoMEU&usp=sharing

**Comment by ant478** [comment]
Может готовую документацию закидывать в вики?

**Comment by ant478** [comment]
И, если можно, PSD-шки тоже.

**Comment by dmowski** [comment]
Общая папка со всем нарисованным
https://drive.google.com/folderview?id=0B_bWgyWObsZBbF9yTHFTeXNwMmc&usp=sharing
